[project]
name = "freedb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-limiter>=3.9.2",
    "flask>=3.1.0",
    "flask-mysql>=1.6.0",
]
